#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "sort.h"

void print_star(int number){
	int i;
	printf("  ");
	for (i = 0; i < number; i++){
		printf("*");
	}
	printf("\n");
}

void print_array(int array[], int size){
	int i;int j;
	printf("\n");
	for (i = 0; i < size; i++){
		printf("%d ",array[i]);
	}
	printf("\n\n");
}

void print_array_star(int array[], int size){
	int i;int j;
	printf("\n");
	printf("Index  Value\n");
	for (i = 0; i < size; i++){
		printf("%2d %6d",i,array[i]);
		print_star(array[i]);
	}
	printf("\n");
}

void insertion_sort (int array[],int size,int limit){
	int i;
	for(i=1;i<size;i++){
		int hole = i;
		int value = array[i];
		while(hole>0 && array[hole-1] > value){
				array[hole]=array[hole-1];
				hole = hole-1;
		}
		array[hole] = value;
		printf("Array after positioning element %d at index  array[%d]\n",array[i],i );
		if(limit<=20){
		print_array_star(array,size);
		}else{
			print_array(array,size);
		}	
	}
	printf("\n Array after sorting using insertion sort \n");
	if(limit<=20){
		print_array_star(array,size);
	}else{
		print_array(array,size);
	}
}

void counting_sort(int array[],int size,int limit){
	int max = array[0];int i;
	printf("Array before sorting\n");
	if(limit<=20){
		print_array_star(array,size);
	}else{
		print_array(array,size);
	}
	//finding size of new array to take count of all possible elements till max value generated by rand function

	for(i=1;i<size;i++){
		if(array[i]>max){
			max=array[i];
		}
	}

	printf("The highest element in the original array which gives us the size of the auxillary array to be created is %d\n ",max);
	
	int sizeOfArray1= max + 1;
	int array1[sizeOfArray1];

	//initializing new array with zero for purpose of counting the occurence of each elements from original array
	for(i=0;i<sizeOfArray1;i++){
		array1[i]=0;
	}

	//incrementing the index value of new array for corrspnding occurences of element found in original array

		for(i=0;i<size;i++){
		array1[array[i]]++;
	}

	printf("Below is the auxillary array whose index represents the element present in original array.\nValue at every index represents the occurences of each element\n");

	//printing the new array which indicates the occurence of each element of original array at its index
	
	if(limit<=20){
		print_array_star(array1,sizeOfArray1);
	}else{
		print_array(array1,sizeOfArray1);
	}
	for(i=0;i<sizeOfArray1;i++){
		array1[i]=array1[i-1] +array1[i];
	}
	printf("Below is the new auxillary array whose index represents the element present in original array.\nThe value at every index represents the no.of elements which are less than or equal to the value present at its index \ni.e value of the original array\n");
	if(limit<=20){
		print_array_star(array1,sizeOfArray1);
	}else{
		print_array(array1,sizeOfArray1);
	}
	int res[size];
	for(i=0;i<size;i++){
		res[i]=0;
	}
	//print_array_star(array1,sizeOfArray1);
	
	//placing each elements from original array starting from backwards to the res array using newarray1.
	//step1: taking value at specific index from original array
	//step2: lookup the value of auxillary array at index=value of original array
	//step3: lookup the index of resultant array = vlaue at index of auxillary array obtained from previous step
	//step4: plae the value of original array at index of resultant array obtained fom previous

	
	for(i=(size-1);i>=0;i--){
		printf("Putting element %d from original array at index %d in resultant array",array[i],array1[array[i]]-1);
		res[array1[array[i]]-1] = array[i];
		array1[array[i]] =array1[array[i]]-1;
		if(limit<=20){
			print_array_star(res,size);
		}else{
			print_array(res,size);
		}
	}
	printf("\n Array after sorting using counting sort \n");
	if(limit<=20){
	print_array_star(res,size);
	}else{
		print_array(res,size);
	}
}

void merge_sort(int array[],int size,int limit){
	if(size>=2){
	printf("Entered into merge_sort");
	if(limit<=20){
		print_array_star(array,size);
	}else{
		print_array(array,size);
	}
	int mid;int i;
	mid = (size/2);
	int left [mid];int right[size-mid];

	for(i=0;i<mid;i++){

		left[i]=array[i];
	}
	for(i=mid;i<size;i++){

		right[i-mid]=array[i];
	}
	merge_sort(left,mid,limit);
	merge_sort(right,(size-mid),limit);
	merge(left,mid,right,(size-mid),array,limit);
	}


	printf("\n Array after sorting using merge sort \n");
	if(limit<=20){
	print_array_star(array,size);
	}else{
		print_array(array,size);
	}

}

void merge (int left[],int left_length,int right[],int right_length, int array[],int limit){
	printf("Entered into merge\n");
	printf("left array");
	print_array_star(left,left_length);
	if(limit<=20){
		print_array_star(left,left_length);
	}else{
		print_array(left,left_length);
	}
	printf("right array");
	if(limit<=20){
		print_array_star(right,right_length);
	}else{
		print_array(right,right_length);
	}
	int  i,j,k;
	i=0;j=0;k=0;
	while (i < left_length && j < right_length){

		if (left[i]<right[j]){
			array[k]=left[i];
			i++;k++;
		}
		else{

			array[k]=right[j];
			j++;k++;
		}
	}

	while (i < left_length){
		array[k]=left[i];
		i++;k++;
	}

	while (j < right_length){
		array[k]=right[j];
		j++;k++;
	}
}

void quick_sort(int array[],int start,int end,int limit){
	if(start<end){
		printf("Entering quick sort\n");
		int partition_index = random_partition_index(array,start,end,limit);
		printf("partition index is %d\n" ,partition_index);
		if(limit<=20){
			print_array_star(array,(end-start+1));
		}else{
			print_array(array,(end-start+1));
		}
		quick_sort(array,start,(partition_index-1),limit);
		quick_sort(array,(partition_index+1),end,limit);
	}
}


int partition_index(int array[],int start,int end,int limit){
	printf("Entering into partition index function .\nTo find partition index and sort elements to the left and right of pivot\n");
	int partition_index = start;
	int pivot = array[end];
	int i;
	for(i=start;i<end;i++){
		if(array[i]<pivot){
			int temp = array[i];
			array[i]=array[partition_index];
			array[partition_index]=temp;
			if(limit<=20){
				print_array_star(array,(end-start+1));
			}else{
				print_array(array,(end-start+1));
			}
			partition_index++;
		}
	}
	int temp2 = array[end];
	array[end]=array[partition_index];
	array[partition_index]=temp2;
	return partition_index;
}

int random_partition_index(int array[],int start,int end,int limit){
	int temp3;
	srand(time(NULL));
	int random_pivot =rand()%(end - start +1) + start;
	printf("Value at random_pivot index is %d\n",array[random_pivot] );
	temp3 = array[end];
	array[end]= array[random_pivot];
	array[random_pivot]=temp3;
	return partition_index(array,start,end,limit);
}